### ISSUE TITLE
Verifier Install Failure on Ubuntu-16.04

### ISSUE THREAD

**Issue by darkn3rd** [jcftang-r7/busser-testinfra#1]
When using bento vagrant box for Ubuntu-16.04, the `kitchen verify` fails because the installation fails.

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
suites:
  - name: default
    run_list:
      - recipe[hello_web::default]
```

The Installer will try to do:

```bash
pip install testinfra
```

But there is not pip command on the system, and so this fails.  An error is never raised from this, and so the test continue to go forward and run.  Also, despite failed installation, the systems think `testinfra` is installed, it never checks again to see if `testinfra` is installed.

```bash
testinfra --verbose /tmp/verifier/suites/testinfra/test_default.py
```

Which naturally fails again, because there is no `testinfra` on the system.

This behavior also happens on other distros as well.  I tried `freebsd-11.2` and `centos-7`.
